var GAME_LEVELS = [
  ["                                                                                        ",
 "                                                                                          ",
 "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy ",
 "xxx!!!!!!!!!!!!!!!!!!!!!!!!!!                                                             ",
 "xxx          v                                                                            ",
 "xxx                                                        A                              ",
 "xxx                       w                                                               ",
 "xxx                            D                                                          ",
 "xxx                           xxx                                                         ",
 "xxx                           xxx        o                                                ",
 "xxx                     o !!! xxx       xxx                                               ",
 "xxx                   xxx !!! xxx                                                       xx",
 "xxx                w  xxx !!! xxx      xxxxx                         o                  xx",
 "xxx              o !! xxx !!! xxx                   yyy      xxx    yxy    xxx          xx",
 "xxx             xx !! xxx !!! xxx         C                                             xx",
 "xxx         o   xx !! xxx !!! xxx                  o    o                           oo  xx",
 "xxx  @     xx!!xxx !! xxx !!! xxx   x  x  x  x  x xxxxxxxx    ^             ^     xxxxxxxx",
 "xxxxxxxxxxxxx!!xxx !! xxx !!! xxx                 xxxxxxxx !!!!!!!!!!!!!!!!!!!!!! xxxxxxxx",
 "xxyyyyyyyyyyy!!xxx !! xxx !!! xxx !!!!!!!!!!!!!!! xxxxxxxx !!!!!!!!!!!!!!!!!!!!!! xxxxxxxx",
 "xxxxxxxxxxxxx!!xxx !! xxx !!! xxx !!!!!!!!!!!!!!! xxxxxxxx !!!!!!!!!!!!!!!!!!!!!! xxxxxxxx",],
  ["                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "xxx  @                              x  o A o   x                                   ",
   "xxx                          xxxx      xx xx       xxxx                           ",
   "xxx                       xx!!!!!!!!!!!!!!!!!!!!!!!!!xx                           ",
   "xxx                       xx!!!!!!!!!!!!!!!!!!!!!!!!!xx                           ",
   "xxx                    xxxxxx!xxxx!xxxx!xxxx!xxxx!xxxxxxx           o             ",
   "xxx                      w                                     x    x    x        ",
   "xxx                         w                                                     ",
   "xxx              o             w                  o    o          x    x          ",
   "xxx             xx                 w           xxxxxxxxxxxx                       ",
   "xxx      o                            w          ^      ^                    x    ",
   "xxx     xx                               w                                   x  o ",
   "xxx             D                                                       x    x  o ",
   "xxx           xxxxx      o   o    o    o             x            x     x    x  o ",
   "xxx           xxxxx    xxxxxxxxxxxxxxxxxxxx                       x     x  o xxxxx",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                xxxxxxxxxxxxxxxxxxx",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx      o         xxxxxxxxxxxxxxxxxxx",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx  xxx    xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                    x                                                                ",
   "   y    y    y                                      x                                                                ",
   " @                                                  x                                                                ",
   " xxxx       xxxx                                    x                                                                ",
   " xxxx       xxxx                                    x                                                                ",
   " xxxx       xxxx  ooo                               x       y    y    y    y                                         ",
   " xxxx     A xxxx                                    x                                                                ",
   " xxxx       xxxx                    C    xxx     xxxx xxxxxxxxxxxxxxxxxxxxx                o  o                      ",
   " xxxx       xxxxxxxxxxx          xxxxxxxxx          xxxxx                                 xxxxxx  x  x  x  x  x      ",
   " xxxx   x   xxxx                 xxxxxx             xxxxx                                                     x      ",
   " xxxx       xxxx           xxxxxxxx         x      W  xxx      y      y        oo                             x      ",
   " xxxx       xxxx           xxxxxxxxxxxx          xxxxxxxx                    xxxxxx            ^  ^           x   o  ",
   " xxxx A     xxxx       xxxxxxxxxxxx      x     x     xxxx                                                     x      ",
   " xxxxo      xxxx           xxxxxxxx              W   xxxxx                            xxx     y         y     x   o  ",
   " xxxxxx     xxxx oo        xxxxxxxx         W        xxxxxxxxxxxxx                                            x      ",
   " xxxx       xxxxxxx             xxx  o            o  xxxxx                            www          y          x   o  ",
   " xxxx       xxxx       ^        xxxxxxx    x    xxxxxxxxxx   A                       x   x    y         y     x      ",
   " xxxx       xxxx       o        xxx    w   w    w    xxxxx                                         y          x   o  ",
   " xxxx   o   xxxx                xxx                  xxxxx                             o                      x      ",
   " xxxx   x   xxxx      xxx     o xxx                  xxxxx            xxx!!!xxx       xxx     y         y     x   o  ",
   " xxxx       xxxx             A  xxx                  xxxxx   A            v                                   x      ",
   " xxxx A     xxxx o        xxxxxxxxx    x        x    xxxxx                                                    x   o  ",
   " xxxx  A    xxxxxx        xxxxxxxx         o        xxxxxx                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxx       xxxx          xxxxxxxxx        xx        xxxxx                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxx       xxxx          xxxxxxxxx                  xxxxx                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxxx     xxxxx       xxxxxxxxxxxx   xxx  W   xxx   xxxxx                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxx       xxxx       A xxxxxxxxxx       W W        xxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxx       xxxxxx       xxxxxxxxxx    o        o    xxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxx       xxxx         xxxxxxxxxx                  xxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxx       y  y         xxxxxxxxxxxx      o                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " xxxx   oDo            o xxxxxxxxxx      xxxxx                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                                                                         ",
   "                                                                                                         ",
   "  A                                                                                                      ",
   "   A            y       y   yyy    y     y       y                y  y  y      y                         ",
   "   A   A         y     y   y   y   y     y       y      y y       y  y  yy     y                         ",
   "   A   A  A       y   y   y     y  y     y       y      y y       y  y  y y    y                         ",
   "   A   A  A        y y    y     y  y     y       y      y  y      y  y  y  y   y           Thanks        ",
   "   A   A            y     y     y  y     y       y     y    y     y  y  y   y  y             for         ",
   "   A  A             y     y     y  y     y        y   y      y   y   y  y    y y           Playing       ",
   "   A                y      y   y    y   y          y y        y y    y  y     yy                         ",
   " A                  y       yyy      yyy            y          y     y  y      y      By:                ",
   "       @                                                                              Rebecca Biegalski  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "                                                                                                         "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
